// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojdvqvnvxncbhywycudk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZHZxdm52eG5jYmh5d3ljdWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDQ4NTUsImV4cCI6MjA3MTc4MDg1NX0.myh0LpLhNE9MY161ldksxxd9fgmLcfyJ0c1SfnRchmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});